
CREATE TABLE `GTS_NOTIFICATIONS` (
  `GTS_NOTIFICATION_ID` BIGINT NOT NULL,
  `GTS_NOTIFICATION_EVENT_ID` BIGINT NOT NULL,
  `GTS_NOTIFICATION_MESSAGE` VARCHAR(100) NOT NULL,
  `GTS_NOTIFICATION_RECEIVER_USER_ID` BIGINT DEFAULT NULL,
  `GTS_NOTIFICATION_RECEIVER_ROLE_ID` INT NOT NULL,
  `GTS_NOTIFICATION_DATE` DATE NOT NULL,
 `gts_notification_timezone_id` INT NOT NULL,
  PRIMARY KEY(GTS_NOTIFICATION_ID),
  FOREIGN KEY(GTS_NOTIFICATION_EVENT_ID) REFERENCES `GTS_NOTIFICATION_EVENTS`(GTS_NOTIFICATION_EVENT_ID)
   );

INSERT INTO GTS_NOTIFICATIONS (GTS_NOTIFICATION_ID,GTS_NOTIFICATION_EVENT_ID,GTS_NOTIFICATION_MESSAGE,GTS_NOTIFICATION_RECEIVER_USER_ID,GTS_NOTIFICATION_RECEIVER_ROLE_ID,GTS_NOTIFICATION_DATE)
VALUES (1,23,"LOOKING FOR A JOB",21,32,"10-12-2020");

INSERT INTO GTS_NOTIFICATIONS (GTS_NOTIFICATION_ID,GTS_NOTIFICATION_EVENT_ID,GTS_NOTIFICATION_MESSAGE,GTS_NOTIFICATION_RECEIVER_USER_ID,GTS_NOTIFICATION_RECEIVER_ROLE_ID,GTS_NOTIFICATION_DATE)
VALUES (1,23,"LOOKING FOR A JOB IN JAVA DEVELOPER",22,33,"11-12-2020");